version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app/./nuxt:/var/www/nuxt
      - ./app/node_modules:/var/www/nuxt/node_modules
    command: npm run dev